//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Movie_Cs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        public int Movie_Id { get; set; }
        public string Movie_Name { get; set; }
        public string Movie_Director { get; set; }
        public string Movie_Description { get; set; }
        public byte[] Data_Image { get; set; }
        public string Movie_Image_Name { get; set; }
    }
}
