//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Movie_Cs
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieOrder
    {
        public int OrderId { get; set; }
        public string MovieName { get; set; }
        public int NumOftickets { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
    }
}
